apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash
  template:
    metadata:
      labels:
        app: hash
    spec: 
      volumes: 
        - name: hash-vol
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: hashfind
          image: 4925k/hashfind:v2
          env: 
            - name: GREET
              valueFrom:
                configMapKeyRef:
                  name: hash-data
                  key: greet
          volumeMounts:
            - name: hash-vol
              mountPath: /usr/src/app/files
              subPath: hash
          imagePullPolicy: Always
        - name: hash-gen
          image: 4925k/hash-gen:v1
          volumeMounts:
            - name: hash-vol
              mountPath: /usr/src/app/files
              subPath: hash
          imagePullPolicy: Always