apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todolistfe
            port: 
              number: 2345
      - path: /todos/create
        pathType: Prefix
        backend:
          service:
            name: todolistfe
            port: 
              number: 2345
      - path: /todos
        pathType: Prefix
        backend:
          service:
            name: todolistbe
            port:
              number: 2344
      - path: /hash/status
        pathType: Prefix
        backend:
          service:
            name: hash
            port:
              number: 2346
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: pingpong
            port: 
              number: 2347
          
