apiVersion: v1
kind: Service
metadata:
  name: todolist-svc
spec:
  type: NodePort
  selector:
    app: todolist
  ports:
    - name: http
      nodePort: 30080 # port available to the outside 
      protocol: TCP
      port: 1234 # cluster port
      targetPort: 3000 # application port