apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/dwk-env/deployment.yaml
  - manifests/dwk-env/service.yaml

images:
  - name: PROJECT/NAME
    newName: jakousa/colorcontent