apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
spec: 
  type: ClusterIP
  selector:
    app: pingpong
  ports: 
    - port: 2347
      protocol: TCP
      targetPort: 4445

# apiVersion: v1
# kind: Service
# metadata:
#   name: pingpong
# spec: 
#   type: ClusterIP
#   selector:
#     app: pingpong
#   ports:
#     - port: 2347
#       protocol: TCP
#       targetPort: 4445

## Load Balancer way for GCP
# apiVersion: v1
# kind: Service
# metadata:
#   name: pingpong
# spec:
#   type: LoadBalancer
#   selector:
#     app: pingpong
#   ports:
#     - port: 2347
#       protocol: TCP
#       targetPort: 4445