name: Release application 

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKECLUSTER: dwk-gke
  GKEZONE: asia-south2-a
  IMAGE: dwk-environments

jobs: 
  build-publish-deploy:
    name: Build, Publish and Deploy
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret
          # project_id:  ${{ secrets.GKE_PROJECT }}
          # workload_identity_provider: 'projects/1027301796219/locations/global/workloadIdentityPools/github/providers/my-repo/github'
          # service_account: 'github-actions@dwk-gke-417116.iam.gserviceaccount.com'


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true
      
      - run: gcloud components install gke-gcloud-auth-plugin
      - run: gcloud --quiet auth configure-docker

      - run : gcloud container clusters get-credentials $GKECLUSTER --zone=$GKEZONE

      - name: Build
        run: |-
           docker build \
           --tag 4925k/hash \
           .

      - name: Publish
        run: |-
            docker push "4925k/hash

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      
      - name: Deploy
        run: |-
          kustomize edit set image gcr.io/PROJECT_ID/IMAGE=gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $IMAGE
          kubectl get services -o wide


